#!/usr/bin/bash

echo "starting collection script..."
#sleep 15
LABEL="INXI-COLLECT"
UUID=$(cat /sys/class/net/$(ip route show default | awk '/default/ {print $5}')/address)
export HOST="http://meowmachine.dyn.vkm.maschinenbau.tu-darmstadt.de:8000/stat"

#mount config
if grep -qs " $LABEL " /proc/mounts; then
    echo "Filesystem with label '$LABEL' is already mounted."
  else
    DEVICE=$(blkid -L "$LABEL" 2>/dev/null)
    if [ -z "$DEVICE" ]; then
      echo "Filesystem with label '$LABEL' not found."
    else 
      DEVICE=$(echo "$DEVICE" | awk -F ':' '{print $1}')
      mkdir -p /mnt/$LABEL
      mount "$DEVICE" /mnt/$LABEL
    fi
fi

#overwrite config
if [ -f "/mnt/$LABEL/envconf" ]; then
  source "/mnt/$LABEL/envconf"
fi

export INXI_JSON=$(inxi -JFfdlmopt --output json --output-file print | python3 -m json.tool | sed 's/".*#/"/')

echo $INXI_JSON | curl  -X POST -H "Content-Type: application/json" -T - "$HOST/$UUID"

